### ISSUE TITLE
Make hook type available in env

### ISSUE THREAD

**Issue by anmuel** [RSCSCybersecurity/captain_hoog#13]
I would like to achieve the following scenario:

Create a Hookin that runs one or many configurable commands and exits once one's status code is not 0.

The set of commands may diverge based on the hook type, i.e. I want to run different commands on pre-push and on pre-commit or post-checkout.
Tho I do not want to create a Hookin for each command because I only care about the status code.

To make it more plastic here's how I imagine a hoogfile configuration for this scenario within a node project:

```yaml
pre-commit:
  - test command
pre-push:
  - test-command
post-checkout:
  - test-command

test-command:
  pre-commit:
    - npm run lint
  pre-push:
    - npm run test
  post-checkout:
    - npm install
```

This may be achieved when the Hookin can determine the type of the git hook and intersect it within its own test logic to only fetch and run the commands for the specified config.
That way we may be very flexible for our hooks because we can reuse the same hookin *test-command* but apply different commands for each use case. I guess this satisfies a lot of default use cases out of the box without the need for special Hookins.

I may even imagine that captain_hoog comes with this kind of Hookin by default.
